# Site settings
title: Crafting Ruby
email: jeroen@craftingruby.com
description: >
  A Ruby on Rails blog covering RoR features and solutions to uncommon problems.
baseurl: "" # the subpath of your site, e.g. /blog/
url:  "http://craftingruby.com" # the base hostname & protocol for your site
twitter_username: fivedigit
github_username:  fivedigit

# Build settings
markdown: kramdown

gems:
  - jekyll-gist
  - jekyll-redirect-from
  - jekyll-sitemap
  - jemoji

permalink: /posts/:year/:month/:day/:title.html
